DROP DATABASE IF EXISTS `VENTAEMPLEADOS`;
CREATE DATABASE `VENTAEMPLEADOS`;
USE `VENTAEMPLEADOS`;

-- CREACION DE LA TABLA DE USUARIO ---
CREATE TABLE `USUARIO`(
CEDULA DOUBLE NOT NULL,
NOMBRE VARCHAR(700) NOT NULL,
ROL VARCHAR(300) NOT NULL,
CLAVE VARCHAR(2000) NOT NULL,
PREGUNTA VARCHAR(500) NOT NULL,
RESPUESTA VARCHAR(2000) NOT NULL,
USUARIO_ACTIVADO DOUBLE NOT NULL,
USUARIO_VERIFICADO DOUBLE NOT NULL,
FECHA_REGISTRO DATETIME NOT NULL,
ULTIMO_INGRESO DATETIME NOT NULL,
CONTACTO VARCHAR(1000) NOT NULL,
PRIMARY KEY(CEDULA));

-- CREACION DE LA TABLA DE CATEGORIA ---
CREATE TABLE `CATEGORIA`(
CODIGO_CATEGORIA DOUBLE NOT NULL AUTO_INCREMENT,
NOMBRE_CATEGORIA VARCHAR(700) NOT NULL,
DISPONIBILIDAD DOUBLE NOT NULL,
PRODUCTOS_VINCULADOS DOUBLE NOT NULL,
PRODUCTOS_DISPONIBLES DOUBLE NOT NULL,
PRIMARY KEY(CODIGO_CATEGORIA));

-- CREACION DE LA TABLA DE PRODUCTO ---
CREATE TABLE `PRODUCTO`(
CODIGO_PRODUCTO DOUBLE NOT NULL,
NOMBRE_PRODUCTO VARCHAR(700) NOT NULL,
IMAGEN_PRINCIPAL VARCHAR(1000) NOT NULL,
IVA DOUBLE NOT NULL,
DESCUENTO DOUBLE NOT NULL,
PRECIO_BASE DOUBLE NOT NULL,
DETALLES VARCHAR(3000) NOT NULL,
PRODUCTO_DISPONIBLE DOUBLE NOT NULL,
ESTADO_PRODUCTO DOUBLE NOT NULL,
ID_CATEGORIA DOUBLE NOT NULL,
PRIMARY KEY(CODIGO_PRODUCTO),
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(CODIGO_CATEGORIA));

-- CREACION DE LA TABLA DE AUXILIAR PRODUCTO INFORMACION---
CREATE TABLE `PRODUCTO_INFORMACION`(
NOMBRE_ESTILO VARCHAR(700) NOT NULL,
TIPO_CONTENIDO DOUBLE NOT NULL,
CONTENIDO VARCHAR(1000) NOT NULL,
IMAGEN_EXTRA VARCHAR(1000) NOT NULL, 
INFORMACION_ADICIONAL VARCHAR(3000) NOT NULL,
DISPONIBLE DOUBLE NOT NULL,
STOCK DOUBLE NOT NULL,
ID_PRODUCTO DOUBLE NOT NULL,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO));

-- CREACION DE LA TABLA VENTA --
CREATE TABLE `VENTA`(
CODIGO_VENTA DOUBLE NOT NULL AUTO_INCREMENT,
FECHA_VENTA DATETIME NOT NULL,
VALOR_IVA DOUBLE NOT NULL,
VALOR_DESCUENTO DOUBLE NOT NULL,
VALOR_TOTAL DOUBLE NOT NULL,
ESTADO_VENTA DOUBLE NOT NULL,
OBSERVACIONES VARCHAR(2000),
CEDULA_USUARIO DOUBLE NOT NULL,
PRIMARY KEY(CODIGO_VENTA),
FOREIGN KEY (CEDULA_USUARIO) REFERENCES USUARIO(CEDULA));

-- CREACION DE LA TABLA ITEM --
CREATE TABLE `ITEM`(
NOMBRE_ITEM VARCHAR(1600) NOT NULL,
INFORMACION_ADICIONAL VARCHAR(3000) NOT NULL,
DESCUENTO DOUBLE NOT NULL,
IVA DOUBLE NOT NULL,
CANTIDAD DOUBLE NOT NULL,
VALOR_BASE DOUBLE NOT NULL,
VALOR_IVA DOUBLE NOT NULL,
VALOR_DESCUENTO DOUBLE NOT NULL,
VALOR_TOTAL DOUBLE NOT NULL,
ID_PRODUCTO DOUBLE NOT NULL,
ID_VENTA DOUBLE NOT NULL,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO),
FOREIGN KEY (ID_VENTA) REFERENCES VENTA(CODIGO_VENTA));

-- CREACION DE LA TABLA APLICACION --
CREATE TABLE `APLICACION`(
CODIGO_APLICACION DOUBLE NOT NULL,
EMAIL_APP VARCHAR(1000) NOT NULL,
CLAVE_DINAMICA VARCHAR(100) NOT NULL,
LISTA_EMAIL VARCHAR(3000) NOT NULL,
CARPETA_IMAGENES VARCHAR(4000) NOT NULL,
CARPETA_COMPRAS VARCHAR(4000) NOT NULL,
PRIMARY KEY (CODIGO_APLICACION));

-- CREACION TABLA DE ALERTAS --
CREATE TABLE `ALERTAS`(
CODIGO_ALERTA DOUBLE NOT NULL,
TITULO VARCHAR(500) NOT NULL,
INFORMACION VARCHAR(1000) NOT NULL,
ID_APLICACION DOUBLE NOT NULL,
PRIMARY KEY(CODIGO_ALERTA),
FOREIGN KEY (ID_APLICACION) REFERENCES APLICACION(GODIGO_APLICACION));

-- CREACION TABLA DE HISTORIAL --
CREATE TABLE `HISTORIAL`(
NIVEL_RIESGO DOUBLE NOT NULL,
FECHA DATETIME NOT NULL,
INFORMACION VARCHAR(5000) NOT NULL,
CEDULA_USUARIO DOUBLE NOT NULL,
NOMBRE VARCHAR(700) NOT NULL);

ALTER TABLE `CATEGORIA` AUTO_INCREMENT = 1;
ALTER TABLE `VENTA` AUTO_INCREMENT = 1;