-------------------- procedimiento buscar usuarios ----------
DROP PROCEDURE IF EXISTS `PROCEDURE_LISTAR_USUARIO`;

DELIMITER $$
CREATE PROCEDURE `PROCEDURE_LISTAR_USUARIO`(IN VAR_CEDULA DOUBLE)
BEGIN
	DECLARE VACIO DOUBLE;
	SET VACIO = (SELECT IFNULL(VAR_CEDULA, 0));
	IF(VACIO != 0) THEN
		SELECT * 
		FROM USUARIO
		WHERE CEDULA = VAR_CEDULA;
	ELSE 
		SELECT * 
		FROM USUARIO;
	END IF;
END $$
DELIMITER ;