-- BUSCAR O LISTAR USUARIOS --
DROP PROCEDURE IF EXISTS `PROCEDURE_LISTAR_VENTAS`;

DELIMITER $$
CREATE PROCEDURE `PROCEDURE_LISTAR_VENTAS`(IN VAR_VENTA DOUBLE)
BEGIN
	DECLARE DEC_VACIO DOUBLE;
	SET DEC_VACIO = (SELECT IFNULL(VAR_VENTA, 0));
	IF(DEC_VACIO != 0) THEN
		SELECT 
			ITEM.NOMBRE_ITEM AS "ITEM_NOMBRE_ITEM",
			ITEM.INFORMACION_ADICIONAL AS "ITEM_INFORMACION_ADICIONAL",
			ITEM.DESCUENTO AS "ITEM_DESCUENTO",
			ITEM.IVA AS "ITEM_IVA",
			ITEM.CANTIDAD AS "ITEM_CANTIDAD",
			ITEM.VALOR_BASE AS "ITEM_VALOR_BASE",
			ITEM.VALOR_IVA AS "ITEM_VALOR_IVA",
			ITEM.VALOR_DESCUENTO AS "ITEM_VALOR_DESCUENTO",
			ITEM.VALOR_TOTAL AS "ITEM_VALOR_TOTAL",
			ITEM.ID_PRODUCTO AS "ITEM_ID_PRODUCTO",
			VENTA.CODIGO_VENTA AS "VENTA_CODIGO_VENTA",
			VENTA.FECHA_VENTA AS "VENTA_FECHA_VENTA",
			VENTA.VALOR_IVA AS "VENTA_VALOR_IVA",
			VENTA.VALOR_DESCUENTO AS "VENTA_VALOR_DECUENTO",
			VENTA.VALOR_TOTAL AS "VENTA_VALOR_TOTAL",
			VENTA.ESTADO_VENTA AS "VENTA_ESTADO_VENTA",
			VENTA.OBSERVACIONES AS "VENTA_OBSERVACIONES",
			VENTA.CEDULA_USUARIO AS "VENTA_CEDULA_USUARIO",
			USUARIO.NOMBRE AS "USUARIO_NOMBRE",
			USUARIO.CONTACTO AS "USUARIO_CONCTACTO"
		FROM VENTA
		INNER JOIN ITEM ON VENTA.CODIGO_VENTA = ITEM.ID_VENTA
		INNER JOIN USUARIO ON VENTA.CEDULA_USUARIO = USUARIO.CEDULA
		WHERE VENTA.CODIGO_VENTA = VAR_VENTA
		ORDER BY VENTA.FECHA_VENTA DESC;
	ELSE 
		SELECT 
			ITEM.NOMBRE_ITEM AS "ITEM_NOMBRE_ITEM",
			ITEM.INFORMACION_ADICIONAL AS "ITEM_INFORMACION_ADICIONAL",
			ITEM.DESCUENTO AS "ITEM_DESCUENTO",
			ITEM.IVA AS "ITEM_IVA",
			ITEM.CANTIDAD AS "ITEM_CANTIDAD",
			ITEM.VALOR_BASE AS "ITEM_VALOR_BASE",
			ITEM.VALOR_IVA AS "ITEM_VALOR_IVA",
			ITEM.VALOR_DESCUENTO AS "ITEM_VALOR_DESCUENTO",
			ITEM.VALOR_TOTAL AS "ITEM_VALOR_TOTAL",
			ITEM.ID_PRODUCTO AS "ITEM_ID_PRODUCTO",
			VENTA.CODIGO_VENTA AS "VENTA_CODIGO_VENTA",
			VENTA.FECHA_VENTA AS "VENTA_FECHA_VENTA",
			VENTA.VALOR_IVA AS "VENTA_VALOR_IVA",
			VENTA.VALOR_DESCUENTO AS "VENTA_VALOR_DECUENTO",
			VENTA.VALOR_TOTAL AS "VENTA_VALOR_TOTAL",
			VENTA.ESTADO_VENTA AS "VENTA_ESTADO_VENTA",
			VENTA.OBSERVACIONES AS "VENTA_OBSERVACIONES",
			VENTA.CEDULA_USUARIO AS "VENTA_CEDULA_USUARIO",
			USUARIO.NOMBRE AS "USUARIO_NOMBRE",
			USUARIO.CONTACTO AS "USUARIO_CONCTACTO"
		FROM VENTA
		INNER JOIN ITEM ON VENTA.CODIGO_VENTA = ITEM.ID_VENTA
		INNER JOIN USUARIO ON VENTA.CEDULA_USUARIO = USUARIO.CEDULA
		ORDER BY VENTA.FECHA_VENTA DESC;
	END IF;
END $$
DELIMITER ;

-- REGISTAR VENTA --
DROP PROCEDURE IF EXISTS `PROCEDURE_INGRESAR_VENTA`;

DELIMITER $$
CREATE PROCEDURE `PROCEDURE_INGRESAR_VENTA`
	(IN VAR_VALORIVA DOUBLE, IN VAR_VALORDESCUENTO DOUBLE, IN VAR_VALORTOTAL DOUBLE, IN VAR_ESTADOVENTA DOUBLE, IN VAR_OBSERVACIONES VARCHAR(2000), IN VAR_CEDULA DOUBLE)
BEGIN
	DECLARE DEC_FECHA DATETIME;
	SET DEC_FECHA = NOW();
	
	INSERT INTO VENTA(CODIGO_VENTA, FECHA_VENTA, VALOR_IVA, VALOR_DESCUENTO, VALOR_TOTAL, ESTADO_VENTA, OBSERVACIONES, CEDULA_USUARIO)
	VALUES (NULL, DEC_FECHA, VAR_VALORIVA, VAR_VALORDESCUENTO, VAR_VALORTOTAL, VAR_ESTADOVENTA, VAR_OBSERVACIONES, VAR_CEDULA);

	SELECT * FROM VENTA WHERE FECHA_VENTA = DEC_FECHA AND (VALOR_TOTAL = VAR_VALORTOTAL AND CEDULA_USUARIO = VAR_CEDULA);
END $$
DELIMITER ;

-- MOFDIFICAR ESTADO COMPRA --
DROP PROCEDURE IF EXISTS `PROCEDURE_MODIFICAR_ESTADOVENTA`;

DELIMITER $$
CREATE PROCEDURE `PROCEDURE_MODIFICAR_ESTADOVENTA`
	(IN VAR_CODIGO DOUBLE, IN VAR_ESTADOVENTA DOUBLE, IN VAR_CEDULA DOUBLE)
BEGIN
	UPDATE VENTA
	SET ESTADO_VENTA = VAR_ESTADOVENTA
	WHERE CODIGO_VENTA = VAR_CODIGO AND CEDULA_USUARIO = VAR_CEDULA;

	SELECT * FROM VENTA WHERE CODIGO_VENTA = VAR_CODIGO AND CEDULA_USUARIO = VAR_CEDULA;
END $$
DELIMITER ;

-- MODIFICAR COMPRA --
DROP PROCEDURE IF EXISTS `PROCEDURE_MODIFICAR_VENTA`;

DELIMITER $$
CREATE PROCEDURE `PROCEDURE_MODIFICAR_VENTA`
	(IN VAR_CODIGO DOUBLE, IN VAR_VALORIVA DOUBLE, IN VAR_VALORDESCUENTO DOUBLE, IN VAR_VALORTOTAL DOUBLE, IN VAR_ESTADOVENTA DOUBLE, IN VAR_CEDULA DOUBLE)
BEGIN
	UPDATE VENTA
	SET VALOR_IVA = VAR_VALORIVA, 
	VALOR_DESCUENTO = VAR_VALORDESCUENTO,
	VALOR_TOTAL = VAR_VALORTOTAL,
	ESTADO_VENTA = VAR_ESTADOVENTA
	WHERE CODIGO_VENTA = VAR_CODIGO AND CEDULA_USUARIO = VAR_CEDULA;

	DELETE FROM ITEM WHERE ID_VENTA = VAR_CODIGO;
	SELECT * FROM VENTA WHERE CODIGO_VENTA = VAR_CODIGO AND CEDULA_USUARIO = VAR_CEDULA;
END $$
DELIMITER ;